import { theme as light } from './theme';

const darkPalette = {
  black: '#0D0D0F',
  darkElevated: '#1A1A1F',
  darkSurface: '#23232A',
  darkCard: '#2A2A33',
  darkBorder: '#3A3A45',
  darkText: '#F2F2F7',
  darkTextSecondary: '#AEAEB8',
  darkTextMuted: '#7A7A85',
  darkOverlay: 'rgba(0,0,0,0.7)',
};

export const darkTheme: typeof light = {
  ...light,
  colors: {
    ...light.colors,
    primary: '#8B7CFA',
    primaryDeep: '#6A49FA',
    primarySoft: '#2D2A4A',
    primaryGlow: 'rgba(139,124,250,0.25)',
    secondary: '#3A5A7A',
    secondarySoft: '#1A2A3A',
    tertiary: '#5A3A4A',
    tertiarySoft: '#3A2A3A',
    success: '#34D376',
    successSoft: '#1A3A2A',
    warning: '#FBBF24',
    warningSoft: '#3A2A1A',
    danger: '#F87171',
    dangerSoft: '#3A1A1A',
    bg: {
      primary: darkPalette.black,
      secondary: darkPalette.darkElevated,
      tertiary: darkPalette.darkSurface,
      elevated: darkPalette.darkSurface,
      card: darkPalette.darkCard,
      sheet: darkPalette.darkSurface,
      overlay: darkPalette.darkOverlay,
      focus: '#0D0D0F',
      focusElevated: '#1A1A1F',
      input: darkPalette.darkSurface,
      greenTint: '#1A3A2A',
      orangeTint: '#3A2A1A',
      purpleTint: '#2D2A4A',
      blueTint: '#1A2A3A',
    },
    text: {
      primary: darkPalette.darkText,
      secondary: darkPalette.darkTextSecondary,
      muted: darkPalette.darkTextMuted,
      disabled: '#5A5A65',
      onAccent: '#FFFFFF',
      onLight: darkPalette.darkText,
      onFocus: '#FFFFFF',
      onFocusMuted: 'rgba(255,255,255,0.65)',
    },
    accent: {
      ...light.colors.accent,
      primary: '#8B7CFA',
      purple: '#8B7CFA',
      lavender: '#2D2A4A',
      brand: '#6A49FA',
      greenSoft: '#1A3A2A',
      blueSoft: '#1A2A3A',
      orangeSoft: '#3A2A1A',
      pinkSoft: '#3A2A3A',
      purpleSoft: '#2D2A4A',
    },
    border: {
      subtle: 'rgba(255,255,255,0.06)',
      soft: 'rgba(255,255,255,0.10)',
      medium: 'rgba(255,255,255,0.15)',
      strong: 'rgba(255,255,255,0.25)',
      solid: darkPalette.darkBorder,
    },
    status: {
      ...light.colors.status,
      info: '#60A5FA',
    },
    gradient: light.colors.gradient,
    purple: '#8B7CFA',
    purpleDeep: '#6A49FA',
    purpleSoft: '#2D2A4A',
    skyBlue: '#3A5A7A',
    softPink: '#5A3A4A',
    background: darkPalette.black,
    surface: darkPalette.darkCard,
    surfaceTint: darkPalette.darkSurface,
    textMuted: darkPalette.darkTextMuted,
    textSecondary: darkPalette.darkTextSecondary,
    info: '#60A5FA',
    green: '#34D376',
    blue: '#60A5FA',
    red: '#F87171',
    orange: '#FBBF24',
    card: darkPalette.darkCard,
    shadow: 'rgba(0,0,0,0.3)',
  },
  shadow: {
    ...light.shadow,
    soft: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 4,
    },
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 3,
    },
    float: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.4,
      shadowRadius: 24,
      elevation: 8,
    },
    glow: {
      shadowColor: '#8B7CFA',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 6,
    },
    hero: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 0.3,
      shadowRadius: 30,
      elevation: 10,
    },
    button: {
      shadowColor: '#8B7CFA',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.2,
      shadowRadius: 14,
      elevation: 5,
    },
  },
};

export const COLORS_DARK = {
  primary: darkTheme.colors.primary,
  primaryDark: darkTheme.colors.primaryDeep,
  primaryLight: darkTheme.colors.primarySoft,
  success: darkTheme.colors.success,
  successLight: darkTheme.colors.successSoft,
  danger: darkTheme.colors.danger,
  dangerLight: darkTheme.colors.dangerSoft,
  warning: darkTheme.colors.warning,
  warningLight: darkTheme.colors.warningSoft,
  background: darkTheme.colors.bg.primary,
  bgPrimary: darkTheme.colors.bg.primary,
  bgSecondary: darkTheme.colors.bg.secondary,
  surface: darkTheme.colors.bg.secondary,
  card: darkTheme.colors.bg.card,
  border: darkTheme.colors.border.soft,
  text: darkTheme.colors.text.primary,
  textSecondary: darkTheme.colors.text.secondary,
  textMuted: darkTheme.colors.text.muted,
  protein: darkTheme.colors.success,
  carbs: darkTheme.colors.warning,
  fat: darkTheme.colors.primary,
  purple: darkTheme.colors.primary,
  orange: darkTheme.colors.warning,
  green: darkTheme.colors.success,
  blue: '#60A5FA',
  red: darkTheme.colors.danger,
  mint: darkTheme.colors.success,
  teal: '#14B8A6',
  bgCard: darkTheme.colors.bg.card,
  bgElevated: darkTheme.colors.bg.elevated,
  textPrimary: darkTheme.colors.text.primary,
  borderMid: darkTheme.colors.border.medium,
  bgInput: darkTheme.colors.bg.input,
};
