export const NAME_CANONICAL_MAP: Record<string, string> = {
  'paneer': 'Paneer',
  'daal': 'Dal',
  'dal': 'Dal',
  'roti': 'Chapati',
  'phulka': 'Chapati',
  'chawal': 'Cooked Rice',
  'bhaat': 'Cooked Rice',
  'dahi': 'Curd',
  'ghee': 'Ghee',
  'aloo': 'Potato',
  'bhindi': 'Okra',
  'baingan': 'Eggplant',
  'bharta': 'Baingan Bharta',
  'biryani': 'Chicken Biryani',
  'pulao': 'Vegetable Pulao',
  'pulav': 'Vegetable Pulao',
  'kheer': 'Rice Pudding',
  'raita': 'Raita',
  'chai': 'Tea',
  'masala chai': 'Tea',
  'lassi': 'Lassi',
  'makhani': 'Butter Chicken',
  'korma': 'Chicken Korma',
  'tandoori': 'Chicken Tandoori',
  'seekh': 'Seekh Kebab',
  'kofta': 'Malai Kofta',
  'palak': 'Palak Paneer',
  'saag': 'Palak Paneer',
  'idli': 'Idli',
  'dosa': 'Dosa',
  'vada': 'Vada',
  'uttapam': 'Uttapam',
  'sambar': 'Sambar',
  'rasam': 'Rasam',
  'chutney': 'Coconut Chutney',
  'puri': 'Puri',
  'bhaji': 'Pav Bhaji',
  'bhel': 'Bhel Puri',
  'sev': 'Sev Puri',
  'dabeli': 'Dabeli',
  'vada pav': 'Vada Pav',
  'samosa': 'Samosa',
  'pakora': 'Pakora',
  'pakode': 'Pakora',
  'kachori': 'Kachori',
  'dhokla': 'Dhokla',
  'thepla': 'Thepla',
  'paratha': 'Paratha',
  'naan': 'Naan',
  'kulcha': 'Naan',
  'poori': 'Puri',
  'upma': 'Upma',
  'poha': 'Poha',
  'sheera': 'Sheera',
  'halwa': 'Halwa',
  'gulab': 'Gulab Jamun',
  'rasgulla': 'Rasgulla',
  'jalebi': 'Jalebi',
  'barfi': 'Barfi',
  'ladoo': 'Ladoo',
  'kesari': 'Kesari Bath',

  'wheate flour': 'Wheat Flour',
  'wheate': 'Wheat',
  'chiken': 'Chicken Breast',
  'chiken breast': 'Chicken Breast',
  'chicken breast': 'Chicken Breast',
  'chkn': 'Chicken Breast',
  'veggies': 'Mixed Vegetables',
  'veg': 'Mixed Vegetables',
  'vege': 'Mixed Vegetables',
  'curd': 'Curd',
  'yogurt': 'Curd',
  'yoghurt': 'Curd',
  'briyani': 'Chicken Biryani',
  'biriyani': 'Chicken Biryani',
  'nan': 'Naan',
  'roti canai': 'Chapati',

  'coke': 'Coca-Cola',
  'coca cola': 'Coca-Cola',
  'pepsi': 'Pepsi',
  'sprite': 'Sprite',
  'fanta': 'Fanta',
  'oreo': 'Oreo Cookies',
  'oreos': 'Oreo Cookies',
  'maggie': 'Maggi Noodles',
  'maggi': 'Maggi Noodles',
  'noodle': 'Instant Noodles',
  'noodles': 'Instant Noodles',
  'ramen': 'Instant Noodles',
  'oat': 'Oats',
  'oats': 'Oats',
  'avo': 'Avocado',
  'avacado': 'Avocado',
  'adacado': 'Avocado',
  'broccli': 'Broccoli',
  'brocolli': 'Broccoli',
  'cauli': 'Cauliflower',
  'cauliflwr': 'Cauliflower',
  'capsicum': 'Bell Pepper',
  'bell pepper': 'Bell Pepper',
  'sweet potato': 'Sweet Potato',
  'sweet potatoe': 'Sweet Potato',
  'zuchini': 'Zucchini',
  'zucchini': 'Zucchini',
  'courgette': 'Zucchini',
  'aubergine': 'Eggplant',
  'egg plant': 'Eggplant',
  'brinjal': 'Eggplant',
  'mushroom': 'Mushrooms',
  'mushrom': 'Mushrooms',
  'tomato': 'Tomato',
  'tomatos': 'Tomatoes',
  'potato': 'Potato',
  'potatos': 'Potatoes',
  'french fry': 'French Fries',
  'french fries': 'French Fries',
  'fries': 'French Fries',
  'chips': 'French Fries',
  'burger': 'Hamburger',
  'ham burger': 'Hamburger',
  'cheeseburger': 'Cheeseburger',
  'pizza': 'Pizza',
  'pasta': 'Pasta',
  'spagetti': 'Spaghetti',
  'spaghetti': 'Spaghetti',
  'mac n cheese': 'Mac and Cheese',
  'mac and cheese': 'Mac and Cheese',
  'sandwhich': 'Sandwich',
  'sandwich': 'Sandwich',
  'toast': 'Toast',
  'omlette': 'Omelette',
  'omlet': 'Omelette',
  'scrambled': 'Scrambled Eggs',
  'fried egg': 'Fried Egg',
  'boiled egg': 'Boiled Egg',
  'egg': 'Egg',
  'eggs': 'Eggs',
  'whey': 'Whey Protein',
  'whey protein': 'Whey Protein',
  'protein shake': 'Whey Protein',
  'protein powder': 'Whey Protein',
  'smoothie': 'Fruit Smoothie',
  'salmon': 'Salmon',
  'tuna': 'Tuna',
  'sardine': 'Sardines',
  'mackarel': 'Mackerel',
  'prawn': 'Prawns',
  'shrimp': 'Prawns',
  'fish': 'Fish Fillet',
  'steak': 'Beef Steak',
  'beef': 'Beef',
  'chicken': 'Chicken',
  'pork': 'Pork',
  'mutton': 'Mutton',
  'lamb': 'Lamb',
  'bacon': 'Bacon',
  'sausage': 'Sausage',
  'ham': 'Ham',
  'salami': 'Salami',
  'butter': 'Butter',
  'cheese': 'Cheese',
  'mayo': 'Mayonnaise',
  'mayonnaise': 'Mayonnaise',
  'ketchup': 'Ketchup',
  'mustard': 'Mustard',
  'bbq sauce': 'BBQ Sauce',
  'hot sauce': 'Hot Sauce',
  'soy sauce': 'Soy Sauce',
  'vinegar': 'Vinegar',
  'olive oil': 'Olive Oil',
  'coconut oil': 'Coconut Oil',
  'vege oil': 'Vegetable Oil',
  'vegetable oil': 'Vegetable Oil',
  'canola oil': 'Canola Oil',
  'sunflower oil': 'Sunflower Oil',
  'honey': 'Honey',
  'maple syrup': 'Maple Syrup',
  'sugar': 'White Sugar',
  'brown sugar': 'Brown Sugar',
  'salt': 'Salt',
  'pepper': 'Black Pepper',
  'black pepper': 'Black Pepper',

  'apple': 'Apple',
  'orange': 'Orange',
  'banana': 'Banana',
  'bananna': 'Banana',
  'mango': 'Mango',
  'grapes': 'Grapes',
  'strawberry': 'Strawberries',
  'strawberries': 'Strawberries',
  'blueberry': 'Blueberries',
  'blueberries': 'Blueberries',
  'raspberry': 'Raspberries',
  'watermelon': 'Watermelon',
  'muskmelon': 'Muskmelon',
  'pineapple': 'Pineapple',
  'papaya': 'Papaya',
  'pomegranate': 'Pomegranate',
  'guava': 'Guava',
  'kiwi': 'Kiwi',
  'lemon': 'Lemon',
  'lime': 'Lime',
  'coconut': 'Coconut',
  'dates': 'Dates',
  'fig': 'Figs',
  'prunes': 'Prunes',
  'raisins': 'Raisins',
  'almond': 'Almonds',
  'almonds': 'Almonds',
  'badam': 'Almonds',
  'walnut': 'Walnuts',
  'walnuts': 'Walnuts',
  'cashew': 'Cashews',
  'cashews': 'Cashews',
  'kaju': 'Cashews',
  'pista': 'Pistachios',
  'pistachio': 'Pistachios',
  'peanut': 'Peanuts',
  'peanuts': 'Peanuts',
  'mungfali': 'Peanuts',
  'kishmish': 'Raisins',

  'rice': 'Cooked Rice',
  'white rice': 'Cooked Rice',
  'basmati rice': 'Cooked Rice',
  'brown rice': 'Brown Rice',
  'quinoa': 'Quinoa',
  'wheat': 'Wheat',
  'whole wheat': 'Whole Wheat',
  'flour': 'Wheat Flour',
  'maida': 'White Flour',
  'atta': 'Whole Wheat Flour',
  'sooji': 'Semolina',
  'rava': 'Semolina',
  'semolina': 'Semolina',
  'corn': 'Corn',
  'maize': 'Corn',
  'makki': 'Corn',
  'popcorn': 'Popcorn',
  'bajra': 'Bajra',
  'jowar': 'Jowar',
  'ragi': 'Ragi',
  'nachni': 'Ragi',
};

export function canonicalizeFoodName(rawName: string): string {
  const lower = rawName.toLowerCase().trim();
  for (const [misspelling, canonical] of Object.entries(NAME_CANONICAL_MAP)) {
    if (lower === misspelling || lower.includes(misspelling + ' ') || lower.startsWith(misspelling + ' ')) {
      return canonical;
    }
  }
  return rawName.replace(/\b\w/g, c => c.toUpperCase());
}
