import json, codecs, sys

with codecs.open(r'D:\FitnessApp\assets\food_database.json', 'r', encoding='utf-8-sig') as f:
    data = json.load(f)

existing_names = {e['food_name'] for e in data}

new_entries = [
    {"food_name": "wheat flour (atta)", "aliases": ["wheat flour", "atta", "whole wheat flour", "gehu ka atta"], "calories_per_100g": 341, "protein_per_100g": 12, "carbs_per_100g": 70, "fat_per_100g": 1.7, "fiber_per_100g": 2.7, "serving_size": "1 roti=40g", "serving_grams": 40, "category": "grains"},
    {"food_name": "maida (refined flour)", "aliases": ["maida", "refined flour", "all-purpose flour", "white flour"], "calories_per_100g": 348, "protein_per_100g": 10, "carbs_per_100g": 73, "fat_per_100g": 0.9, "fiber_per_100g": 0, "serving_size": "1 tbsp=10g", "serving_grams": 10, "category": "grains"},
    {"food_name": "besan (chickpea flour)", "aliases": ["besan", "chickpea flour", "gram flour", "channe ka atta"], "calories_per_100g": 360, "protein_per_100g": 22, "carbs_per_100g": 54, "fat_per_100g": 6, "fiber_per_100g": 6, "serving_size": "1 cup=100g", "serving_grams": 100, "category": "grains"},
    {"food_name": "cooked basmati rice", "aliases": ["basmati rice cooked", "steamed basmati rice", "cooked rice"], "calories_per_100g": 130, "protein_per_100g": 2.7, "carbs_per_100g": 28, "fat_per_100g": 0.3, "fiber_per_100g": 0.4, "serving_size": "1 cup cooked=150g", "serving_grams": 150, "category": "grains"},
    {"food_name": "raw basmati rice", "aliases": ["basmati rice raw", "uncooked basmati rice", "raw rice"], "calories_per_100g": 349, "protein_per_100g": 7.5, "carbs_per_100g": 78, "fat_per_100g": 0.4, "fiber_per_100g": 0, "serving_size": "1 cup raw=190g", "serving_grams": 190, "category": "grains"},
    {"food_name": "cooked dal (yellow lentil)", "aliases": ["cooked dal", "yellow dal", "yellow lentil cooked", "toor dal cooked"], "calories_per_100g": 116, "protein_per_100g": 9, "carbs_per_100g": 20, "fat_per_100g": 0.4, "fiber_per_100g": 3.5, "serving_size": "1 katori=150g", "serving_grams": 150, "category": "legumes"},
    {"food_name": "masoor dal (red lentil cooked)", "aliases": ["masoor dal", "red lentil cooked", "masoor dal cooked"], "calories_per_100g": 116, "protein_per_100g": 9, "carbs_per_100g": 20, "fat_per_100g": 0.4, "fiber_per_100g": 0, "serving_size": "1 katori=150g", "serving_grams": 150, "category": "legumes"},
    {"food_name": "chana dal (cooked)", "aliases": ["chana dal", "bengal gram cooked", "split chickpea cooked"], "calories_per_100g": 164, "protein_per_100g": 9, "carbs_per_100g": 27, "fat_per_100g": 5, "fiber_per_100g": 4, "serving_size": "1 katori=150g", "serving_grams": 150, "category": "legumes"},
    {"food_name": "moong dal (cooked)", "aliases": ["moong dal", "yellow moong dal cooked", "split green gram cooked"], "calories_per_100g": 105, "protein_per_100g": 7, "carbs_per_100g": 19, "fat_per_100g": 0.4, "fiber_per_100g": 3, "serving_size": "1 bowl=150g", "serving_grams": 150, "category": "legumes"},
    {"food_name": "rajma cooked (kidney beans)", "aliases": ["rajma", "kidney beans cooked", "red kidney beans"], "calories_per_100g": 140, "protein_per_100g": 9, "carbs_per_100g": 24, "fat_per_100g": 0.5, "fiber_per_100g": 6, "serving_size": "1 katori=150g", "serving_grams": 150, "category": "legumes"},
    {"food_name": "chole (chickpeas cooked)", "aliases": ["chole", "chickpeas cooked", "chickpea curry", "kabuli chana"], "calories_per_100g": 164, "protein_per_100g": 9, "carbs_per_100g": 27, "fat_per_100g": 3, "fiber_per_100g": 7, "serving_size": "1 katori=150g", "serving_grams": 150, "category": "legumes"},
    {"food_name": "paneer (full fat)", "aliases": ["paneer", "full fat paneer", "Indian cottage cheese"], "calories_per_100g": 265, "protein_per_100g": 18, "carbs_per_100g": 3, "fat_per_100g": 20, "fiber_per_100g": 0, "serving_size": "1 piece 50g=50g", "serving_grams": 50, "category": "dairy"},
    {"food_name": "paneer (low fat)", "aliases": ["low fat paneer", "diet paneer", "skinny paneer"], "calories_per_100g": 180, "protein_per_100g": 18, "carbs_per_100g": 5, "fat_per_100g": 9, "fiber_per_100g": 0, "serving_size": "1 piece 50g=50g", "serving_grams": 50, "category": "dairy"},
    {"food_name": "tofu (firm)", "aliases": ["tofu", "firm tofu", "bean curd", "soya paneer"], "calories_per_100g": 76, "protein_per_100g": 8, "carbs_per_100g": 2, "fat_per_100g": 4, "fiber_per_100g": 0, "serving_size": "1 cup=126g", "serving_grams": 126, "category": "protein"},
    {"food_name": "chapati (wheat, no oil)", "aliases": ["chapati", "roti", "phulka", "wheat roti", "tandoori roti"], "calories_per_100g": 297, "protein_per_100g": 9, "carbs_per_100g": 52, "fat_per_100g": 7, "fiber_per_100g": 3, "serving_size": "1 roti=40g", "serving_grams": 40, "category": "indian_bread"},
    {"food_name": "chapati (wheat, with oil)", "aliases": ["chapati with oil", "oil roti", "ghee roti", "roti with ghee"], "calories_per_100g": 320, "protein_per_100g": 9, "carbs_per_100g": 52, "fat_per_100g": 10, "fiber_per_100g": 3, "serving_size": "1 roti=40g", "serving_grams": 40, "category": "indian_bread"},
    {"food_name": "paratha (plain)", "aliases": ["paratha", "plain paratha", "tawa paratha"], "calories_per_100g": 304, "protein_per_100g": 7, "carbs_per_100g": 45, "fat_per_100g": 11, "fiber_per_100g": 0, "serving_size": "1 paratha=60g", "serving_grams": 60, "category": "indian_bread"},
    {"food_name": "paratha (aloo)", "aliases": ["aloo paratha", "potato paratha", "stuffed paratha aloo"], "calories_per_100g": 210, "protein_per_100g": 5, "carbs_per_100g": 30, "fat_per_100g": 8, "fiber_per_100g": 0, "serving_size": "1 paratha=70g", "serving_grams": 70, "category": "indian_bread"},
    {"food_name": "poha (cooked)", "aliases": ["poha", "flattened rice", "beaten rice", "poha cooked"], "calories_per_100g": 76, "protein_per_100g": 1.5, "carbs_per_100g": 16, "fat_per_100g": 0.4, "fiber_per_100g": 0, "serving_size": "1 bowl=150g", "serving_grams": 150, "category": "grains"},
    {"food_name": "upma (cooked)", "aliases": ["upma", "sooji upma", "rava upma", "suji upma"], "calories_per_100g": 130, "protein_per_100g": 4, "carbs_per_100g": 22, "fat_per_100g": 4, "fiber_per_100g": 0, "serving_size": "1 bowl=180g", "serving_grams": 180, "category": "indian_main"},
    {"food_name": "idli (plain)", "aliases": ["idli", "steamed rice cake", "plain idli", "idly"], "calories_per_100g": 58, "protein_per_100g": 2.5, "carbs_per_100g": 12, "fat_per_100g": 0.4, "fiber_per_100g": 0.5, "serving_size": "1 idli=35g", "serving_grams": 35, "category": "indian_main"},
    {"food_name": "dosa (plain)", "aliases": ["dosa", "plain dosa", "sada dosa", "rice crepe"], "calories_per_100g": 168, "protein_per_100g": 4, "carbs_per_100g": 31, "fat_per_100g": 3, "fiber_per_100g": 1, "serving_size": "1 dosa=80g", "serving_grams": 80, "category": "indian_main"},
    {"food_name": "biryani (chicken)", "aliases": ["chicken biryani", "biryani chicken", "chicken dum biryani"], "calories_per_100g": 173, "protein_per_100g": 9, "carbs_per_100g": 22, "fat_per_100g": 5, "fiber_per_100g": 0, "serving_size": "1 plate=350g", "serving_grams": 350, "category": "indian_main"},
    {"food_name": "biryani (veg)", "aliases": ["veg biryani", "vegetable biryani", "mixed vegetable biryani"], "calories_per_100g": 138, "protein_per_100g": 4, "carbs_per_100g": 24, "fat_per_100g": 3, "fiber_per_100g": 0, "serving_size": "1 plate=300g", "serving_grams": 300, "category": "indian_main"},
    {"food_name": "aloo sabzi (potato curry)", "aliases": ["aloo sabzi", "aloo ki sabzi", "potato curry", "aloo bhaji"], "calories_per_100g": 110, "protein_per_100g": 2, "carbs_per_100g": 18, "fat_per_100g": 4, "fiber_per_100g": 0, "serving_size": "1 katori=150g", "serving_grams": 150, "category": "indian_main"},
    {"food_name": "halwa (suji)", "aliases": ["halwa", "suji halwa", "sooji halwa", "semolina halwa", "rava halwa"], "calories_per_100g": 320, "protein_per_100g": 4, "carbs_per_100g": 48, "fat_per_100g": 13, "fiber_per_100g": 0, "serving_size": "1 katori=100g", "serving_grams": 100, "category": "indian_main"},
    {"food_name": "full fat milk (3.5%)", "aliases": ["full fat milk", "whole milk", "3.5% milk", "full cream milk"], "calories_per_100g": 61, "protein_per_100g": 3.2, "carbs_per_100g": 4.8, "fat_per_100g": 3.5, "fiber_per_100g": 0, "serving_size": "1 glass=200ml", "serving_grams": 200, "category": "dairy"},
    {"food_name": "toned milk (1.5%)", "aliases": ["toned milk", "1.5% milk", "low fat milk", "double toned milk"], "calories_per_100g": 45, "protein_per_100g": 3.2, "carbs_per_100g": 4.8, "fat_per_100g": 1.5, "fiber_per_100g": 0, "serving_size": "1 glass=200ml", "serving_grams": 200, "category": "dairy"},
    {"food_name": "curd/dahi (full fat)", "aliases": ["curd", "dahi", "yogurt full fat", "full fat yogurt", "plain yogurt"], "calories_per_100g": 98, "protein_per_100g": 3.5, "carbs_per_100g": 4.7, "fat_per_100g": 7, "fiber_per_100g": 0, "serving_size": "1 katori=150g", "serving_grams": 150, "category": "dairy"},
    {"food_name": "curd (low fat)", "aliases": ["low fat curd", "low fat dahi", "diet yogurt", "low fat yogurt"], "calories_per_100g": 60, "protein_per_100g": 4, "carbs_per_100g": 6, "fat_per_100g": 1.5, "fiber_per_100g": 0, "serving_size": "1 katori=150g", "serving_grams": 150, "category": "dairy"},
    {"food_name": "greek yogurt (plain)", "aliases": ["greek yogurt", "greek yoghurt", "strained yogurt", "hung curd"], "calories_per_100g": 100, "protein_per_100g": 9, "carbs_per_100g": 6, "fat_per_100g": 3.5, "fiber_per_100g": 0, "serving_size": "1 cup=150g", "serving_grams": 150, "category": "dairy"},
    {"food_name": "whey protein (unflavoured)", "aliases": ["whey protein", "whey powder", "whey isolate", "whey concentrate"], "calories_per_100g": 375, "protein_per_100g": 82, "carbs_per_100g": 5, "fat_per_100g": 4, "fiber_per_100g": 0, "serving_size": "1 scoop=30g", "serving_grams": 30, "category": "protein"},
    {"food_name": "egg whole (boiled)", "aliases": ["whole egg", "boiled egg", "hard boiled egg", "egg whole"], "calories_per_100g": 155, "protein_per_100g": 13, "carbs_per_100g": 1.1, "fat_per_100g": 11, "fiber_per_100g": 0, "serving_size": "1 large egg=50g", "serving_grams": 50, "category": "eggs"},
    {"food_name": "chicken breast (grilled)", "aliases": ["grilled chicken breast", "chicken breat grilled", "skinless chicken breast grilled"], "calories_per_100g": 165, "protein_per_100g": 31, "carbs_per_100g": 0, "fat_per_100g": 3.6, "fiber_per_100g": 0, "serving_size": "1 medium=150g", "serving_grams": 150, "category": "meat"},
    {"food_name": "chicken breast (raw)", "aliases": ["raw chicken breast", "chicken breast uncooked", "boneless chicken breast"], "calories_per_100g": 120, "protein_per_100g": 22, "carbs_per_100g": 0, "fat_per_100g": 3, "fiber_per_100g": 0, "serving_size": "1 medium=150g", "serving_grams": 150, "category": "meat"},
    {"food_name": "chicken leg (with skin, roasted)", "aliases": ["chicken leg", "chicken drumstick", "chicken leg piece", "roasted chicken leg"], "calories_per_100g": 230, "protein_per_100g": 26, "carbs_per_100g": 0, "fat_per_100g": 14, "fiber_per_100g": 0, "serving_size": "1 leg=150g", "serving_grams": 150, "category": "meat"},
    {"food_name": "chicken wings (fried)", "aliases": ["chicken wings", "fried chicken wings", "buffalo wings", "hot wings"], "calories_per_100g": 320, "protein_per_100g": 24, "carbs_per_100g": 10, "fat_per_100g": 21, "fiber_per_100g": 0, "serving_size": "6 pieces=100g", "serving_grams": 100, "category": "meat"},
    {"food_name": "mutton (cooked)", "aliases": ["mutton", "goat meat cooked", "mutton curry", "goat curry"], "calories_per_100g": 250, "protein_per_100g": 25, "carbs_per_100g": 0, "fat_per_100g": 16, "fiber_per_100g": 0, "serving_size": "1 portion=100g", "serving_grams": 100, "category": "meat"},
    {"food_name": "fish (rohu, cooked)", "aliases": ["rohu fish", "rohu cooked", "indian carp cooked", "rohu"], "calories_per_100g": 110, "protein_per_100g": 17, "carbs_per_100g": 0, "fat_per_100g": 4, "fiber_per_100g": 0, "serving_size": "1 piece=80g", "serving_grams": 80, "category": "seafood"},
    {"food_name": "salmon (grilled)", "aliases": ["salmon", "grilled salmon", "salmon fillet", "atlantic salmon"], "calories_per_100g": 208, "protein_per_100g": 20, "carbs_per_100g": 0, "fat_per_100g": 13, "fiber_per_100g": 0, "serving_size": "1 fillet=150g", "serving_grams": 150, "category": "seafood"},
    {"food_name": "tuna (canned in water)", "aliases": ["tuna canned", "canned tuna", "tuna in water", "light tuna"], "calories_per_100g": 116, "protein_per_100g": 26, "carbs_per_100g": 0, "fat_per_100g": 1, "fiber_per_100g": 0, "serving_size": "1/2 can=85g", "serving_grams": 85, "category": "seafood"},
    {"food_name": "prawns/shrimp (cooked)", "aliases": ["prawns", "shrimp", "cooked prawns", "cooked shrimp", "prawn"], "calories_per_100g": 99, "protein_per_100g": 18, "carbs_per_100g": 0.9, "fat_per_100g": 1.1, "fiber_per_100g": 0, "serving_size": "100g", "serving_grams": 100, "category": "seafood"},
    {"food_name": "soya chunks (dry)", "aliases": ["soya chunks", "soy chunks", "textured vegetable protein", "soya nuggets"], "calories_per_100g": 345, "protein_per_100g": 52, "carbs_per_100g": 33, "fat_per_100g": 0.5, "fiber_per_100g": 0, "serving_size": "50g dry=50g", "serving_grams": 50, "category": "protein"},
    {"food_name": "soya chunks (cooked)", "aliases": ["cooked soya chunks", "soya chunks cooked", "soy chunks cooked"], "calories_per_100g": 130, "protein_per_100g": 19, "carbs_per_100g": 13, "fat_per_100g": 0.2, "fiber_per_100g": 0, "serving_size": "1 bowl=150g", "serving_grams": 150, "category": "protein"},
    {"food_name": "peanuts (roasted)", "aliases": ["peanuts", "roasted peanuts", "groundnuts", "mungfali"], "calories_per_100g": 585, "protein_per_100g": 24, "carbs_per_100g": 22, "fat_per_100g": 49, "fiber_per_100g": 0, "serving_size": "1 handful=30g", "serving_grams": 30, "category": "nuts_and_seeds"},
    {"food_name": "banana (medium)", "aliases": ["banana", "medium banana", "ripe banana", "kela"], "calories_per_100g": 89, "protein_per_100g": 1.1, "carbs_per_100g": 23, "fat_per_100g": 0.3, "fiber_per_100g": 2.6, "serving_size": "1 medium=120g", "serving_grams": 120, "category": "fruits"},
    {"food_name": "dates (medjool)", "aliases": ["dates", "medjool dates", "dried dates", "khajoor"], "calories_per_100g": 277, "protein_per_100g": 1.8, "carbs_per_100g": 75, "fat_per_100g": 0.2, "fiber_per_100g": 7, "serving_size": "2 dates=48g", "serving_grams": 48, "category": "fruits"},
    {"food_name": "spinach (raw)", "aliases": ["spinach", "palak", "raw spinach", "baby spinach"], "calories_per_100g": 23, "protein_per_100g": 2.9, "carbs_per_100g": 3.6, "fat_per_100g": 0.4, "fiber_per_100g": 2.2, "serving_size": "1 cup=30g", "serving_grams": 30, "category": "vegetables"},
    {"food_name": "broccoli (cooked)", "aliases": ["broccoli", "cooked broccoli", "broccoli florets"], "calories_per_100g": 35, "protein_per_100g": 2.4, "carbs_per_100g": 7.2, "fat_per_100g": 0.4, "fiber_per_100g": 2.6, "serving_size": "1 cup=156g", "serving_grams": 156, "category": "vegetables"},
    {"food_name": "potato (boiled)", "aliases": ["potato", "boiled potato", "aloo boiled", "cooked potato"], "calories_per_100g": 87, "protein_per_100g": 1.9, "carbs_per_100g": 20, "fat_per_100g": 0.1, "fiber_per_100g": 0, "serving_size": "1 medium=150g", "serving_grams": 150, "category": "vegetables"},
    {"food_name": "sweet potato (boiled)", "aliases": ["sweet potato", "shakarkandi", "boiled sweet potato", "cooked sweet potato"], "calories_per_100g": 86, "protein_per_100g": 1.6, "carbs_per_100g": 20, "fat_per_100g": 0.1, "fiber_per_100g": 0, "serving_size": "1 medium=130g", "serving_grams": 130, "category": "vegetables"},
    {"food_name": "peas (cooked)", "aliases": ["peas", "cooked peas", "green peas", "matar"], "calories_per_100g": 81, "protein_per_100g": 5.4, "carbs_per_100g": 14, "fat_per_100g": 0.4, "fiber_per_100g": 0, "serving_size": "1/2 cup=80g", "serving_grams": 80, "category": "vegetables"},
    {"food_name": "capsicum (bell pepper)", "aliases": ["capsicum", "bell pepper", "shimla mirch", "green pepper"], "calories_per_100g": 31, "protein_per_100g": 1, "carbs_per_100g": 6, "fat_per_100g": 0.3, "fiber_per_100g": 0, "serving_size": "1 medium=119g", "serving_grams": 119, "category": "vegetables"},
    {"food_name": "corn (boiled)", "aliases": ["corn", "boiled corn", "sweet corn", "makkai", "bhutta"], "calories_per_100g": 96, "protein_per_100g": 3.4, "carbs_per_100g": 21, "fat_per_100g": 1.5, "fiber_per_100g": 0, "serving_size": "1 cob=90g", "serving_grams": 90, "category": "vegetables"},
    {"food_name": "mushroom (cooked)", "aliases": ["mushroom", "cooked mushroom", "button mushroom", "khumb"], "calories_per_100g": 28, "protein_per_100g": 2.5, "carbs_per_100g": 4.3, "fat_per_100g": 0.5, "fiber_per_100g": 0, "serving_size": "1 cup=156g", "serving_grams": 156, "category": "vegetables"},
    {"food_name": "bottle gourd (lauki)", "aliases": ["bottle gourd", "lauki", "dudhi", "ghiya", "calabash"], "calories_per_100g": 17, "protein_per_100g": 0.8, "carbs_per_100g": 4, "fat_per_100g": 0.1, "fiber_per_100g": 0, "serving_size": "1 cup=145g", "serving_grams": 145, "category": "vegetables"},
    {"food_name": "bitter gourd (karela)", "aliases": ["bitter gourd", "karela", "bitter melon", "bitter squash"], "calories_per_100g": 34, "protein_per_100g": 3.6, "carbs_per_100g": 7, "fat_per_100g": 0.2, "fiber_per_100g": 0, "serving_size": "1 cup=93g", "serving_grams": 93, "category": "vegetables"},
    {"food_name": "oats (rolled, dry)", "aliases": ["oats", "rolled oats", "dry oats", "old fashioned oats"], "calories_per_100g": 389, "protein_per_100g": 17, "carbs_per_100g": 66, "fat_per_100g": 7, "fiber_per_100g": 11, "serving_size": "1 cup dry=90g", "serving_grams": 90, "category": "grains"},
    {"food_name": "oats (cooked)", "aliases": ["cooked oats", "oatmeal", "oat porridge", "porridge"], "calories_per_100g": 71, "protein_per_100g": 2.5, "carbs_per_100g": 12, "fat_per_100g": 1.5, "fiber_per_100g": 0, "serving_size": "1 bowl=240g", "serving_grams": 240, "category": "grains"},
    {"food_name": "brown rice (cooked)", "aliases": ["brown rice", "cooked brown rice", "brown rice cooked"], "calories_per_100g": 123, "protein_per_100g": 2.7, "carbs_per_100g": 25, "fat_per_100g": 1, "fiber_per_100g": 0, "serving_size": "1 cup cooked=195g", "serving_grams": 195, "category": "grains"},
    {"food_name": "quinoa (cooked)", "aliases": ["quinoa", "cooked quinoa", "quinoa grain"], "calories_per_100g": 120, "protein_per_100g": 4.4, "carbs_per_100g": 22, "fat_per_100g": 1.9, "fiber_per_100g": 2.8, "serving_size": "1 cup=185g", "serving_grams": 185, "category": "grains"},
    {"food_name": "popcorn (plain)", "aliases": ["popcorn", "air popped popcorn", "plain popcorn", "pop corn"], "calories_per_100g": 387, "protein_per_100g": 13, "carbs_per_100g": 78, "fat_per_100g": 4.5, "fiber_per_100g": 0, "serving_size": "1 cup popped=8g", "serving_grams": 8, "category": "snacks"},
    {"food_name": "black coffee (no sugar)", "aliases": ["black coffee", "black coffee no sugar", "espresso black", "plain coffee"], "calories_per_100g": 2, "protein_per_100g": 0.3, "carbs_per_100g": 0, "fat_per_100g": 0, "fiber_per_100g": 0, "serving_size": "1 cup=240ml", "serving_grams": 240, "category": "beverages"},
    {"food_name": "coffee with milk (no sugar)", "aliases": ["coffee with milk", "white coffee", "milk coffee", "latte"], "calories_per_100g": 30, "protein_per_100g": 2, "carbs_per_100g": 3, "fat_per_100g": 1, "fiber_per_100g": 0, "serving_size": "1 cup=240ml", "serving_grams": 240, "category": "beverages"},
    {"food_name": "chai (with milk and sugar)", "aliases": ["chai", "masala chai", "indian tea", "sweet chai"], "calories_per_100g": 80, "protein_per_100g": 2, "carbs_per_100g": 12, "fat_per_100g": 2, "fiber_per_100g": 0, "serving_size": "1 cup=200ml", "serving_grams": 200, "category": "beverages"},
    {"food_name": "orange juice (fresh)", "aliases": ["orange juice", "fresh orange juice", "orange juice fresh", "santra juice"], "calories_per_100g": 45, "protein_per_100g": 0.7, "carbs_per_100g": 10, "fat_per_100g": 0.2, "fiber_per_100g": 0, "serving_size": "1 glass=200ml", "serving_grams": 200, "category": "beverages"},
    {"food_name": "lassi (plain sweet)", "aliases": ["lassi", "sweet lassi", "plain lassi", "punjabi lassi"], "calories_per_100g": 140, "protein_per_100g": 5, "carbs_per_100g": 22, "fat_per_100g": 4, "fiber_per_100g": 0, "serving_size": "1 glass=250ml", "serving_grams": 250, "category": "beverages"},
    {"food_name": "buttermilk (chaas)", "aliases": ["buttermilk", "chaas", "mohi", "spiced buttermilk"], "calories_per_100g": 40, "protein_per_100g": 3, "carbs_per_100g": 5, "fat_per_100g": 0.9, "fiber_per_100g": 0, "serving_size": "1 glass=250ml", "serving_grams": 250, "category": "dairy"},
    {"food_name": "kurkure (masala munch)", "aliases": ["kurkure", "masala munch", "kurkure masala"], "calories_per_100g": 508, "protein_per_100g": 6, "carbs_per_100g": 62, "fat_per_100g": 26, "fiber_per_100g": 0, "serving_size": "1 pack=65g", "serving_grams": 65, "category": "snacks"},
    {"food_name": "maggi noodles (cooked)", "aliases": ["maggi", "maggi noodles", "instant noodles cooked", "maggi cooked"], "calories_per_100g": 154, "protein_per_100g": 4, "carbs_per_100g": 24, "fat_per_100g": 5, "fiber_per_100g": 0, "serving_size": "1 pack cooked=300g", "serving_grams": 300, "category": "snacks"},
    {"food_name": "ketchup (tomato)", "aliases": ["ketchup", "tomato ketchup", "tomato sauce"], "calories_per_100g": 97, "protein_per_100g": 1, "carbs_per_100g": 23, "fat_per_100g": 0.3, "fiber_per_100g": 0, "serving_size": "1 tbsp=17g", "serving_grams": 17, "category": "condiments"},
]

to_add = [e for e in new_entries if e['food_name'] not in existing_names]
print(f'Total new entries defined: {len(new_entries)}')
print(f'Actually missing (to add): {len(to_add)}')
for e in to_add:
    print(f'  ADD: {e["food_name"]}')

data.extend(to_add)
print(f'Total after addition: {len(data)}')

with codecs.open(r'D:\FitnessApp\assets\food_database.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)

print('Done!')
